"""transactions table

Revision ID: 32958da88083
Revises: 668eeb86ddfc
Create Date: 2018-05-03 20:27:03.452264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32958da88083'
down_revision = '668eeb86ddfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'price')
    # ### end Alembic commands ###
